on:
  workflow_call:
    inputs:
      tag-regex:
        description: 'Tag format as regex'
        required: false
        type: string
        default: 'v*.*.*'

jobs:
  release-notes:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Release Notes
        run: sed -n -e "1{/# /d;}" -e "2{/^$/d;}" -e "/# $(git describe --abbrev=0 --exclude="$(git describe --abbrev=0 --match='${{inputs.tag-regex}}' --tags)" --match='${{inputs.tag-regex}}' --tags | tr -d v)/q;p" CHANGELOG.md > release-notes.txt
      - uses: actions/upload-artifact@v3
        with:
          name: release-notes
          path: release-notes.txt
          retention-days: 1
